### ISSUE TITLE
Build fails on Android

### ISSUE THREAD

**Issue by apicgg** [jtvargas/TheLock#19]
Hey @jtvargas . I really appreciate publishing the source code into GitHub. But I am having trouble to run the app into Android device and emulator. Seems like the expo build is getting failed after running `npm run android`. `iOS` is working like a charm.

![Screenshot 2024-05-11 at 11 18 31 AM](https://github.com/jtvargas/TheLock/assets/78271602/d19d77f5-0977-4056-a3fe-59cbc6b5abfd)

Did you encounter this issue and by any chance have solution for this?

**Comment by jtvargas** [comment]
Hey @apicgg to be honest my focus was iOS I didn't have the change to test the app on Android (due to some animation lagging, so I prioritize the iOS build instead of the Android one)

**Comment by apicgg** [comment]
@jtvargas Thanks for your response. I was able to run the build on Android with some modifications. But yes you are right there are some issues with animation lagging.

**Comment by jtvargas** [comment]
feel free to add a PR if is stable and I can prepare a release for android!

@apicgg

**Comment by apicgg** [comment]
Sure, happy to. I will reopen the issue. Thanks.
@jtvargas
